//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IpConfig.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class URLs : global::System.Configuration.ApplicationSettingsBase {
        
        private static URLs defaultInstance = ((URLs)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new URLs())));
        
        public static URLs Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>localhost</string>
  <string>localhost:8080</string>
  <string>202.112.140.210</string>
  <string>192.168.1.209:8080</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection URLStrings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["URLStrings"]));
            }
            set {
                this["URLStrings"] = value;
            }
        }
    }
}
